# Generated by Django 3.2.8 on 2021-11-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211129_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='content_description',
            new_name='products',
        ),
    ]
