# Generated by Django 3.2.8 on 2021-12-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bill_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bills',
            new_name='_bills',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='_firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='password',
            new_name='_password',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='_phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='surname',
            new_name='_surname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='_username',
        ),
    ]
