# Generated by Django 3.2.8 on 2021-12-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211202_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_bills',
            new_name='bills',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_username',
            new_name='username',
        ),
    ]
