# Generated by Django 3.2.8 on 2021-10-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gramaj',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
