# Generated by Django 3.2.8 on 2021-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='typeof',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
