# Generated by Django 3.2.8 on 2021-11-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211103_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sauce',
            old_name='name',
            new_name='title',
        ),
    ]
